### ISSUE TITLE
Disk size is not respected

### ISSUE THREAD

**Issue by efenex** [karmab/kcli#10]
Using a profile like this (with an LVM backend):

```
x:
  template: y
  disks:
    - size: 20
```
gives me disks like:
```
lvs
LV                                          VG   Attr       LSize  Pool Origin                                      Data%  Meta%  Move Log Cpy%Sync Convert
x.iso                                       hdd  -wi-ao----  4.00m                                                                                         
x_1.img                                     hdd  swi-aos---  2.01g      y.qcow2 2.57                                   
y.qcow2                                     hdd  owi-a-s---  2.00g                                    
```

Updating the template to be:

```
x:
  template: y
  disks:
    - size: 200
```
Results in the same size for the disk. Not sure if it's being based on the template size (if so, then why +0.01g?) or issue is elsewhere.
