### ISSUE TITLE
multiple networks and DHCP

### ISSUE THREAD

**Issue by yevgenybulochnik** [karmab/kcli#183]
First, thanks for creating kcli its really cool! I was wondering if its possible to create a setup with two networks and DHCP. When I create a vm and assign the default net + another network(nat and dhcp enabled) the ip addresses never get generated.  When i remove one or the other network from the vm profile everything works fine. 
Also, when I try to create static ips using the net key (with ip, gateway, and mask set) in the vm profile, I end up getting an ssh error, no route to host.
I think some of this is likely my own ignorance in regard to dnsmasq and iptables but any insight is greatly appreciated! 
Ultimately what I want to do is assign a host only accessible ip to each vm to be able to run ansible from the host using that ip, but also have the vm get an ip from my home router via dhcp so the vm is accessible by other computers on the network.  

Thanks again for creating this! Apologize in advance if this doesn't quite make sense, still fairly new to libvirt and some networking concepts in general.

**Comment by yevgenybulochnik** [comment]
Also seem to have encountered a different problem. It seems within plans with a network the dhcp ip addresses are also not assigned. 
Example profile: 
```
devbox:
  image: bionic-server-cloudimg-amd64.img
  pool: testpool
  ansible:
  - playbook: testplay.yml
    verbose: true
    user: ubuntu
small:
  image: bionic-server-cloudimg-amd64.img
  nets:
    - net1
debian8:
  image: debian-8.11.0-openstack-amd64.qcow2
```
Example plan:
```
net1:
  type: network
  cidr: 10.0.0.0/24
  dhcp: true
  nat: true

net2:
  type: network
  cidr: 10.0.1.0/24
  dhcp: true
  nat: true

p1:
  type: profile
  image: bionic-server-cloudimg-amd64.img
  disks:
    - size: 1

vm1:
  profile: p1
  nets:
    - net1

vm2:
  image: bionic-server-cloudimg-amd64.img
  disks:
    - size: 1
  nets:
    - name: net2

vm3:
  profile: small
```
Ouput:
````
+------+--------+------------+----------------------------------+----------+---------+--------+
| Name | Status |    Ips     |              Source              |   Plan   | Profile | Report |
+------+--------+------------+----------------------------------+----------+---------+--------+
| vm1  |   up   |            | bionic-server-cloudimg-amd64.img | testplan |    p1   |        |
| vm2  |   up   |            | bionic-server-cloudimg-amd64.img | testplan |  kvirt  |        |
| vm3  |   up   | 10.0.0.141 | bionic-server-cloudimg-amd64.img | testplan |  small  |        |
+------+--------+------------+----------------------------------+----------+---------+--------+
Listing Networks...
+---------+--------+------------------+------+---------+------+
| Network |  Type  |       Cidr       | Dhcp |  Domain | Mode |
+---------+--------+------------------+------+---------+------+
| default | routed | 192.168.122.0/24 | True | default | nat  |
| net1    | routed |   10.0.0.0/24    | True |   net1  | nat  |
| net2    | routed |   10.0.1.0/24    | True |   net2  | nat  |
+---------+--------+------------------+------+---------+------+
 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
 2020-02-24 09:08:47  52:54:00:0e:88:5e  ipv4      10.0.0.141/24             vm3             ff:b5:5e:67:ff:00:02:00:00:ab:11:e7:12:42:45:e9:d3:a7:ae

 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------

 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
```

The only one that got an ip was vm3, which was from the `small` profile

This is running on ubuntu1804 using the kcli repo

**Comment by karmab** [comment]
not addressing your issue directly but just want to comment i m trying to have a dedicated slack channel (in k8s namespace) to address issues in a more live fashion

**Comment by karmab** [comment]
regarding your issue,  it's due to the fact that:
- you are forcing the primary disk of vms vm1 and vm2 to 1Gb, which prevents them to boot (as their os needs a bigger disk).
- the profile associated to vm3, which is named small, doesnt exist, which results in using a profile without an image, so that doesnt properly boot either. Bare in mind that it's perfectly fine to declare a vm without an associated image.

Still, there is probably room for improvement. Namely,
- tagging  the profile is invalid if somehow the specified disk size is lower than the one needed for an image
- prevents creation of a vm associated to a non existent profile, as it happens if you try to create the vm with `kcli create vm -p small vm3`

**Comment by yevgenybulochnik** [comment]
Makes sense! Appreciate the help. Sorry in hindsight it was pretty silly to set the disks to 1. Changing to 10 does boot the vms and assign the appropriate ips. In the example above the small profile was defined in .kcli/profiles. So that one did boot correctly as it had a default disk size of 8

**Comment by yevgenybulochnik** [comment]
For future reference in case someone has issues with static ips or multiple networks using the `nets` key. Using the `virsh console <vm-name>` (you must set a user password using `cmds`) was helpful to triage issues. For me the Ubuntu bionic image creates network interfaces with the prefix `ens`. It appears the net plan config that is generated for the image used the prefix `eth` which was causing the machine not to get an IP address. Specifying the correct `nic` in a kcli profile or plan fixed this issue for me. 

Example:
```
net1:
  type: network
  cidr: 10.0.0.0/24
  dhcp: true
  nat: true

net2:
  type: network
  cidr: 10.0.1.0/24
  dhcp: true
  nat: true

p1:
  type: profile
  image: bionic-server-cloudimg-amd64.img
  disks:
    - size: 10

vm1:
  profile: p1
  nets:
    - name: net1
       nic: ens3
    - name: net2
       nic: ens4
```

When only one net is used this is not an issue because of how the netplan config is setup if you are only using one interface.

**Comment by karmab** [comment]
i believe commit https://github.com/karmab/kcli/commit/cb06c525de233f82afff0ebb195b33b6acdc5ce3 should remove the need for specifying the nic and allows you to use a slightly simpler plan.
I was addressing the ens* prefix only when image started by ubuntu* and have extended to the full set of ubuntu+debian images (for which i believe the same nomenclature should be in used)

**Comment by yevgenybulochnik** [comment]
Nice! Working great, but seems to be skipping the first network in the `nets` array. Including the `nic` key explicitly, does still work for all networks.  Appreciate your support and quick responses! 

Example Plan:
```
net1:
  type: network
  cidr: 10.0.0.0/24
  dhcp: true
  nat: true

net2:
  type: network
  cidr: 10.0.1.0/24
  dhcp: true
  nat: true

net3:
  type: network
  cidr: 10.0.2.0/24
  dhcp: true
  nat: true

p1:
  type: profile
  image: bionic-server-cloudimg-amd64.img
  disks:
    - size: 10
  # ansible:
  #   - playbook: testplay.yml
  #     verbose: true
  #     user: ubuntu

vm1:
  profile: p1
  nets:
    - net1
    - net2
    - net3
  cmds:
    - echo "ubuntu:ubuntu#1" | chpasswd
```

Vm1 netplan config:
```
# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    ethernets:
        ens4:
            dhcp4: true
        ens5:
            dhcp4: true
    version: 2
```
