### ISSUE TITLE
[usage] How to attach a VM in libvirt to a bridge instead a network?

### ISSUE THREAD

**Issue by e-minguez** [karmab/kcli#220]
According to the docs:

```
nets: Array of networks to define. For each of them, you can specify just a string for the name, or a dict containing name, public and alias and ip, mask and gateway
```

But in libvirt you can attach a VM directly to a bridge such as:

```
<interface type="bridge">
  <mac address="52:54:00:60:5c:86"/>
  <source bridge="bridge0"/>
  <target dev="vnet0"/>
  <model type="virtio"/>
  <alias name="net0"/>
  <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
</interface>
```

Can kcli VMs be attached to a bridge?

Thanks

**Comment by karmab** [comment]
sure, here's an example on the comand line
`kcli create vm -P nets=[localnet] alonso`
where localnet is your bridge

**Comment by e-minguez** [comment]
Gotcha, thanks.
Can this be specified in the docs somewhere? Like in the 'net' parameter section.
Thanks!

**Comment by e-minguez** [comment]
Can parameters be overriden when creating the VM? Let me try to explain myself.

Current profile:
```
centos-8:
  image: CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64.qcow2
  numcpus: 2
  cpuhotplug: true
  cpumodel: "host-passthrough"
  memory: 4096
  memoryhotplug: true
  disks:
  - size: 20
  nets:
  - name: default
  cmds:
  - echo unix1234 | passwd --stdin centos
```

I want those parameters to be the defaults but for some VMs I want to override them at build time, such as:

```
$ kcli create vm -p centos-8 -P memory=8192 -P cpus=4 -P nets=[bridge0] test01
```

But it seems it doesn't work:

```
$ kcli info vm
Using test01 from local as vm
name: test01
creationdate: 24-08-2020 12:47
status: up
autostart: False
image: CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64.qcow2
user: centos
plan: kvirt
profile: centos-8
cpus: 2
memory: 4096
net interface: eth0 mac: 52:54:00:d4:88:c4 net: default type: routed
diskname: vda disksize: 20GB diskformat: file type: qcow2 path: /var/lib/libvirt/images/test01_0.img
```
