### ISSUE TITLE
Can I spin up windows server in vsphere and execute ansible play on it during creating?

### ISSUE THREAD

**Issue by git-dolia** [karmab/kcli#328]
Hi community

Just a quick question.

Can I spin up the windows server in vsphere using kcli plan and execute ansible play on it during creation?

For example, I need to deploy a windows server. I also need to install iis and other software on it. Can I use kcli and ansible together?

**Comment by karmab** [comment]
yes, there are two main ways to do this:
- spin up a vm first (through a plan or not) and then run your playbook using klist.py as dynamic inventory to reach your vm
- directly bundle the playbook in a plan. For instance,

```
testansible:
 image: centos8
 ansible:
  - playbook: prout.yml
    verbose: true
    variables:
     - x: 8
     - z: 12
```

**Comment by karmab** [comment]
here s another example

```
parameters:
 image: centos8

01_myplay:
 type: ansible
 verbose: false
 playbook: prout.yml

testansible01:
 image: {{ image }}
 memory: 1024
 numcpus: 1
 disks:
  - size: 10
 nets:
  - {{ network }}

testansible02:
 image: {{ image }}
 memory: 1024
 numcpus: 1
 disks:
  - size: 10
 nets:
  - {{ network }}
```
