### ISSUE TITLE
`kcli create plan` skips first couple of VM's for no apparent reason

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#368]
I have the following plan:

```yaml
################
# KCLI PROFILE #
################
minio-backup:
  type: profile
  cmds:
    #### Initial prep.
    ## Run as root for the rest of the session
    - sudo -i
    #### Disk prep.
    ## label, partition, mount folders & naming of the disks
    - >
      parted --script /dev/sdb \
        mklabel gpt \
        mkpart primary xfs 0% 100% \
        name 1 minio-data1
    - >
      parted --script /dev/sdc \
        mklabel gpt \
        mkpart primary xfs 0% 100% \
        name 1 minio-data2
    - >
      parted --script /dev/sdd \
        mklabel gpt \
        mkpart primary xfs 0% 100% \
        name 1 minio-data3
    - >
      parted --script /dev/sde \
        mklabel gpt \
        mkpart primary xfs 0% 100% \
        name 1 minio-data4
    - mkdir -v /minio-data1
    - mkdir -v /minio-data2
    - mkdir -v /minio-data3
    - mkdir -v /minio-data4
    ## xfs format all the disks
    - mkfs.xfs /dev/sdb1
    - mkfs.xfs /dev/sdc1
    - mkfs.xfs /dev/sdd1
    - mkfs.xfs /dev/sde1
    ## ensure that the disks are mounted at srv reboot
    - uuid=$(blkid /dev/sdb1 --match-tag UUID --output value)
    - echo "UUID=$uuid /minio-data1 xfs defaults 0 0" >> /etc/fstab
    - uuid=$(blkid /dev/sdc1 --match-tag UUID --output value)
    - echo "UUID=$uuid /minio-data2 xfs defaults 0 0" >> /etc/fstab
    - uuid=$(blkid /dev/sdd1 --match-tag UUID --output value)
    - echo "UUID=$uuid /minio-data3 xfs defaults 0 0" >> /etc/fstab
    - uuid=$(blkid /dev/sde1 --match-tag UUID --output value)
    - echo "UUID=$uuid /minio-data4 xfs defaults 0 0" >> /etc/fstab
    - mount -a
    #### system conf.
    ## calling sysctl applies the conf. in the injected sysctl.conf file
    ## ( see the files section )
    - sysctl -p
    ## Use a specific user for executing MinIO => so that we don't run as root
    - useradd -r miniouser -s /sbin/nologin
    #### MinIO installation
    - wget -O /usr/local/bin/minio https://dl.min.io/server/minio/release/linux-amd64/minio.RELEASE.2021-11-09T03-21-45Z
    - chmod +x /usr/local/bin/minio
    - chown miniouser:miniouser /usr/local/bin/minio
    - chown -R miniouser:miniouser /mnt
    - systemctl enable minio.service
    - systemctl start minio.service
    
  ## push audit configuration files to the server
  files:
  - path: /etc/sysctl.conf
    currentdir: True
    origin: ~/iac-conductor/software-services/minio/vm-cluster/sysctl.conf
  - path: /etc/default/minio
    currentdir: True
    origin: ~/iac-conductor/software-services/minio/vm-cluster/minio
  - path: /etc/systemd/system/minio.service
    currentdir: True
    origin: ~/iac-conductor/software-services/minio/vm-cluster/minio.service

  pool: vmware-pool
  image: ubuntu2004
  domain: my.local
  numcpus: 4
  memory: 16384
  disks:
    - size: 15
      thin: True
    - size: 50
      thin: True
    - size: 50
      thin: True
    - size: 50
      thin: True
    - size: 50
  nested: false

#####################
# KCLI PER VM CONF. #
#####################
#minio-pr-backp-01-vk:
minio-backup-01-v:
  profile: minio-backup
  nets:
  - name: Network
    dns: 192.168.2.21
    gateway: 192.168.22.1
    ip: 192.168.20.206
    mask: 255.255.254.0
    nic: ens192

#minio-pr-backp-02-vk:
minio-backup-02-v:
  profile: minio-backup
  nets:
  - name: Network
    dns: 192.168.2.21
    gateway: 192.168.22.1
    ip: 192.168.20.207
    mask: 255.255.254.0
    nic: ens192

#minio-pr-backp-03-vk:
minio-backup-03-v:
  profile: minio-backup
  nets:
  - name: Network
    dns: 192.168.2.21
    gateway: 192.168.22.1
    ip: 192.168.20.208
    mask: 255.255.254.0
    nic: ens192

#minio-pr-backp-04-vk:
minio-backup-04-v:
  profile: minio-backup
  nets:
  - name: Network
    dns: 192.168.2.21
    gateway: 192.168.22.1
    ip: 192.168.20.209
    mask: 255.255.254.0
    nic: ens192
```

----

As it can be seen in the plan I've commented out the the long server names. As when I deployed the plan with these long names KCLI would report:

```txt
kcli create plan --force --inputfile ./software-services/minio/vm-cluster/plan.yml kubernemlig-prod-backup
Couldn't delete plan folder kubernemlig-prod-backup. Hit (vim.fault.NoPermission) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Permission to perform this operation was denied.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Folder:group-v219732',
   privilegeId = 'Folder.Delete'
}
minio-pr-backp-03-vk deleted on nemlig-vsphere!
Plan kubernemlig-prod-backup deleted!
Deploying Vms...
minio-pr-backp-01-vk skipped on nemlig-vsphere!
minio-pr-backp-02-vk skipped on nemlig-vsphere!
....
```

And then MinIO srv. 03 and 04 are deployed. How come that the first two servers are skipped? If I use the above plan, with the shorter server names - no servers are skipped.

What could be going on here?

---

My KCLI version is at: vcbe8de4 (2021/11/17)

Thank you very much.
