### ISSUE TITLE
ssh key permissions

### ISSUE THREAD

**Issue by bashfulrobot** [karmab/kcli#484]
Hi there, I am trying to use the container on my workstation.

## config.yaml

```
srv:
  host: 192.168.168.1
  pool: default
  protocol: ssh
  type: kvm
  user: dustin
```

## docker run command

```
❯  docker run -v $HOME/.ssh:/root/.ssh -v $HOME/.kcli:/root/.kcli --rm quay.io/karmab/kcli:latest get vm
```

## error

```
Cannot recv data: Bad owner or permissions on /root/.ssh/config: Connection reset by peer
Couldn't connect to client srv. Leaving...
```

## Theory

Now, usually, on the workstation, you would need to have something like the following (for your user):

- `.ssh` directory: 700 (drwx------)
- `public key` (.pub file): 644 (-rw-r--r--)
- `private key` (id_rsa): 600 (-rw-------)

I assume the container is running as root - what is the recommended way to get around this?

Thank you.
