### ISSUE TITLE
Pass Env variable to VM

### ISSUE THREAD

**Issue by ferni7** [karmab/kcli#493]
Is there a way to pass environment variables to a VM via CLI or plan?

**Comment by karmab** [comment]
every parameter provided as uppercase is converted as env variable
I ve added a note in the doc to clarify (https://kcli.readthedocs.io/en/latest/#overriding-parameters)

**Comment by ferni7** [comment]
Thank you, but I must be doing something wrong as it's not working still.

```
parameters:
 image: ubuntu2004

ubuntu-vm:
 image: {{ image }}
 numcpus: 2
 memory: 4096
 disks:
  - size: 100
 nets:
  - name: br0
 TEST_ENV: value_here
```

**Comment by karmab** [comment]
what is parser is the parameters section so in your example, that would rather be

```

parameters:
 image: ubuntu2004
 TEST_ENV: value_here
ubuntu-vm:
 image: {{ image }}
 numcpus: 2
 memory: 4096
 disks:
  - size: 100
 nets:
  - name: br0
```

But I agree putting the env variable at profile level also makes sense so i address it in this commit https://github.com/karmab/kcli/commit/4f993a44cd3f3a8b464beacb44f36b69a46f6624

**Comment by ferni7** [comment]
Thank you sir - putting it int he parameters section works but I need unique values in the VM as well, will wait for that release :)

**Comment by karmab** [comment]
it's already there!

**Comment by ferni7** [comment]
Ok yep I see it now thanks.

Next issue - they show up as available under the user (ubuntu in my case).

But of course when I run a cmd with the plan like this

```
 cmds:
  - /home/ubuntu/test-script.sh
```

Then this command is run as root, and the env variable set isn't available. 
Normally if I was running the script with sudo i could do the following to pass through the user env variables:
`sudo -E  /home/ubuntu/test-script.sh`


Any ideas?

**Comment by karmab** [comment]
I think you can workaround it by explicitely running the following in your script (or in a previous cmd)
`source /etc/profile.d/kcli.sh`

**Comment by ferni7** [comment]
Thanks for the idea - that would work. But I've ended up passing the parameter into the script like this :) 

```
parameters:
 dummy_var: 123
...
 cmds:
  - /home/ubuntu/test-script.sh {{ dummy_var }}
```
