### ISSUE TITLE
Set file permissions for folder

### ISSUE THREAD

**Issue by ferni7** [karmab/kcli#494]
I'm struggling to get the file permissions to flow through to the VM, what am I doing wrong?
Here is the section from my plan.yaml:

```
files:
  - path: /home/ubuntu/scripts/
    origin: ./scripts/
    owner: ubuntu:ubuntu
    mode: 755
```

And here is what it translates to in user-data:
```
cat /mnt/iso/user-data
- owner: root:root
  path: /home/ubuntu/scripts/test.sh
  permissions: '0700'
  content: | 
     #!/bin/bash
....
```

**Comment by karmab** [comment]
right, the permissions apply to files but you're providing a directory.
For directories, the entire list of files is parsed but permissions are not carried over, let me fix that

**Comment by ferni7** [comment]
Ahh I see - Thanks - I've upgraded but still not working?

```
kcli version
version: 99.0 commit: 37a7b4a 2023/01/02 Available Updates: False
```

**Comment by karmab** [comment]
the change allows permissions in the files below the top directory to be correct but dont address permissions for the directory itself.
sadly cloudinit doesnt allow more tweaking to the directory, they get created if missing but that's about all there is too it

**Comment by ferni7** [comment]
Hm, something still not right....

```
 files:
  - path: /home/ubuntu/scripts
    origin: ./scripts/
    owner: ubuntu:ubuntu
    mode: 755
```

The Directory is ending up as:

`drwxr-xr-x 2 root   root    4096 Jan  2 22:24 scripts`

The files in that dir are:

```
ls -la k8s-build-scripts/
total 40
drwxr-xr-x 2 root root 4096 Jan  2 22:24 .
drwxr-xr-x 5 root root 4096 Jan  2 22:27 ..
-rwx------ 1 root root  422 Jan  2 22:24 00-prep.sh
-rwx------ 1 root root  195 Jan  2 22:24 01-install.sh
```
