### ISSUE TITLE
Is there support for changing default username with cloudinit?

### ISSUE THREAD

**Issue by ferni7** [karmab/kcli#495]
Cloud Init supports it like this - is there a way to do this with kcli parameters/plans?

```
#cloud-config
system_info:
  default_user:
    name: ferni7
```
