### ISSUE TITLE
Cannot specify MAC address for openshift-registry VM

### ISSUE THREAD

**Issue by lack** [karmab/kcli#541]
I need to specify specific Mac addresses for our baremetal network DHCP server, and there's no parameters for `kcli create openshift-registry` to specify a specific MAC.

**Comment by karmab** [comment]
I ll expose it in a cleaner way but note you can use vmrules for that matter
So, in your paramfile you could set something like this

```
vmrules:
- mydisconnected-registry:
    nets:
    - name: mynetwork
       mac: xxxxx
    - default 
 ```
