### ISSUE TITLE
Can't set disk format using plans

### ISSUE THREAD

**Issue by chrodriguez** [karmab/kcli#598]
It is possible to create a disk specifying qcow format if disk is created manually:

```
kcli create disk -s 10 -P "format=qcow" -p vms-ssd prueba -n 
```
But when using a plan like:

```
bastion:
  template: ubuntu-22.04
  profile: default
  memory: 4096
  numcpus: 2
  disks:
   - size: 30
  nets:
    - name: dmz
      mac: "aa:aa:aa:aa:bb:00"

bastion-home:
  type: disk
  pool: vms-ssd
  size: 50
  format: qcow
  vms:
    - bastion
 ```

disk format is ignored when [configuring diskentries at kvirt/config.py#L2210](https://github.com/karmab/kcli/blob/54b8687ae328cbf13827493da58b33001a7dd4d3/kvirt/config.py#L2210)

**Comment by karmab** [comment]
Hello,
I think your example is incorrect, It was creating a qcow2 disk because that's the default value, not because of your parameters. In particular, there's no format parameter, for kvm, you either want a qcow or a raw disk, and this is handled through the thin parameter.
So if you want a raw disk, you would pass thin=True
This was not being handled in the command line (it was in the plan) so I've added it now.

About your plan example, I do see a bit of confusion there too
You dont need to use a disk section to plug to a vm beeing created. Disks entries are rather for creating a (shared) disk between several existing vms.

So your example can be simplified to:

```
bastion:
  image: ubuntu-22.04
  memory: 4096
  numcpus: 2
  disks:
   - size: 30
   - thin: true
   - 50
  nets:
    - name: dmz
      mac: "aa:aa:aa:aa:bb:00"
```
This would create a vm based on the ubuntu2204 cloud image and with two disks, the first one beeing raw (non thin) and the second beeing qcow
