### ISSUE TITLE
[GCP Provider] - Public IP is not configurable on deployed GCE VM's.

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#607]
As far as I remember I bumped into this when I deployed K3s clusters on GCP in the early summer this year.

The challenge: Deployed VM's on GCE get a public IP address. I wish to avoid this. The VM's should not be reachable from the outside. Unless the end-user really wants this. At least it should be configurable again.

To avoid this I've tried:

- Configuring: 

```yaml
  - NODE_NAME-worker-0:
      nets:
        - name: GCP_SUBNET_NAME
          ip: IPv4_OF_THE_NODE
          public: false
```

and:

```yaml
gcp:
  type: gcp
  credentials: ~/SOME_CREDS.json
  public: false
  project: PROJECT_NAME
  zone: ZONE_NAME
```

---

None of the above makes the difference. The deployed `VM` is assigned a `public IP` `IPv4`.

I've looked through old commits and issues and found these ones to be of interest:

- [gcp: reports only private ip when public is set to False ](https://github.com/karmab/kcli/commit/f1cdc468b59a5a389076f6fffd9a0d20982d57aa) < you apparently removed this option again
- [gcp: allow to set public at config or parameterfile level](https://github.com/karmab/kcli/commit/1efc1e5aff04102aa7c0127d61f4841ddbf052ef)
- and [gcp: fully remove public](https://github.com/karmab/kcli/commit/f03c573a290b2f73f7394db6ed719bde974b5d94?diff=split)

I also found this issue where I bumped into this previously: [[GCP Provider] SSLError when deploying. Connection timed out](https://github.com/karmab/kcli/issues/548). Where this comment is of specific interest: [issuecomment-1549503945](https://github.com/karmab/kcli/issues/548#issuecomment-1549503945)

---

Can we plz get back the option to configure whether or not deployed GCE VM's should have a public IP or not.

Thank you very much.
