### ISSUE TITLE
Couldnt find basefolder {basefolder}

### ISSUE THREAD

**Issue by nsu700** [karmab/kcli#611]
The `baseFolder` could not be set in the myvsphere section, or it will cause error as below:
```
[root@bastion ~]# kcli create kube openshift --paramfile ocp-parameter.yml ocp-example
Couldnt find basefolder {basefolder}
Couldn't connect to client myvsphere. Leaving...
```

Below is my kcli config
```
[root@bastion ~]# cat .kcli/config.yml
default:
 client: myvsphere
 pool: WorkloadDatastore
 import_network: segment-sandbox-bpszd
 basefolder: /SDDC-Datacenter/Workloads/sandbox-bpszd/

myvsphere:
 type: vsphere
...
 datacenter: SDDC-Datacenter
 filtervms: true
 cluster: Cluster-1
 restricted: True
 basefolder: /SDDC-Datacenter/Workloads/sandbox-bpszd/
```

Moving the basefolder up to under the default section, the error disappeared
