### ISSUE TITLE
openshift: URL for certain in-cluster services is not working when assigned a domain with wildcard resolution

### ISSUE THREAD

**Issue by raptorsun** [karmab/kcli#618]
I had installed Openshift 4.14.2 (stable) in my testing machine using `kcli create cluster openshift --pf parameters_openshift.yml`.
Here is the configuration file:
```yaml
cluster: openshift-dev
version: stable
domain: nailedit.duckdns.org
tag: '4.14'
ctlplanes: 3
workers: 0
memory: 16384
disk_size: 60
numcpus: 4
pull_secret: openshift_pull.json
network: bridge0
api_ip: 192.168.2.170
```
The domain `nailedit.duckdns.org` is pointing to the public IP address my internet provide assigned to me. 

Openshift 4.14 requires the console pod to download a pluging manifest from monitoring-plugin service using the URL `monitoring-plugin.openshift-monitoring.svc.cluster.local`. 
I check the service using this command which timesout. The nslookup inside the console pod is showing the DNS server resolve the name `monitoring-plugin.openshift-monitoring.svc.cluster.local` to my public IP address, instead of the service IP in cluster.   
`kubectl exec console-5c6f466c9d-cgb2k -n openshift-console  -- curl -k https://monitoring-plugin.openshift-monitoring.svc.cluster.local:9443/plugin-manifest.json`
When using nslookup in the console pod, it is resolving the name by appending my domain after the url as `monitoring-plugin.openshift-monitoring.svc.cluster.local.nailedit.duckdns.org`. 

When I using the default domain which is not resolvable by my server, the DNS in cluster is resolving the URL `monitoring-plugin.openshift-monitoring.svc.cluster.local` to the correct service IP address. 

Is there some important parameters missing to make the DNS work correctly?
