### ISSUE TITLE
[Available parameters for client/profile/plan files] example for the keywords

### ISSUE THREAD

**Issue by BurlyLuo** [karmab/kcli#717]
Hello team: can we add an example for the item: https://kcli.readthedocs.io/en/latest/#available-parameters-for-client-profile-plan-files
like cpupinning. we only get it's a list. but can't know how to add the parameter.
have read the source code but not get the clue. 
so if we can add an example for each parameter, it will be nice for the beginner.
```
[root@rowan> kcli]# kcli -d create vm -i centos9stream -P memory=4096 -P numcpus=4 -P disks=[50] -P rootpassword=hive -P nets='[{"name":"brnet","ip":"192.168.2.200","netmask":"24","gateway":"192.168.2.1"},{"name":"vppdpdk5"},{"name":"vppdpdk8"},{"name":"vppdpdk9"}]' -P cmds='["yum -y install nc", "yum -y install net-tools", "yum -y install pciutils", "yum -y install wget", "wget http://192.168.2.100/kvm/tools/lseth -P /usr/bin/" , "chmod +x /usr/bin/lseth" , "yum -y install lrzsz"]' vm1 -s
```

**Comment by karmab** [comment]
you have a point. In the meantime, you can check in the samples repo, in particular in https://github.com/karmab/kcli-plan-samples/blob/main/cputuning/cpu.yml

**Comment by BurlyLuo** [comment]
From the demo we can see it with yaml format. 
```
cpu:
  memory: 512
  cpumodel: core2duo
  cpuflags:
   - name: arat
     enable: false
   - name: avx2
     enable: true
  numcpus: 2
  nets: 
   - default
  pool: default
  image: centos8stream
```
but how do we trans to cmds format?
and which parameter tells the cpuping cpu?
