### ISSUE TITLE
[OpenShift Provisioning] Not correct install-config.yaml format

### ISSUE THREAD

**Issue by nsu700** [karmab/kcli#720]
I am using kcli-99.0.0.git.202409130918.548a812-0.el9.x86_64 on rhel9.4 to provision a 4.12 OpenShift cluster, and hit an error 

```
[lab-user@bastion-6hrbs ~]$ kcli create kube openshift --paramfile parameters.yml ocp
Deploying on client myvsphere
Deploying cluster 6hrbs
Using stable version
Removing existing directory /home/lab-user/.kcli/clusters/6hrbs
Using existing openshift-install found in your PATH
Using installer version 4.12.26
Using image rhcos-412.86.202306132230-0-vmware
ERROR failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: [platform.vsphere.vCenter: Required value: must specify the name of the vCenter, platform.vsphere.username: Required value: must specify the username, platform.vsphere.password: Required value: must specify the password, platform.vsphere.datacenter: Required value: must specify the datacenter, platform.vsphere.defaultDatastore: Required value: must specify the default datastore, platform.vsphere.failureDomains: Forbidden: the TechPreviewNoUpgrade feature set must be enabled to use this field, platform.vsphere.vcenters: Forbidden: the TechPreviewNoUpgrade feature set must be enabled to use this field]
```

Found that it is because the kcli generate the install-config.yaml based on [4.13 format](https://docs.openshift.com/container-platform/4.13/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html#installation-configuration-parameters-additional-vsphere_installing-vsphere-installer-provisioned-customizations), which include some parameters that is not recognized by [4.12 older version](https://docs.openshift.com/container-platform/4.12/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html#installation-configuration-parameters_installing-vsphere-installer-provisioned-customizations). For example in 4.12 there is no `vcenters` parameter, however it is supported in 4.13 and also in the kcli generated install-config.yaml, hence I hit above error, below is the install-config.yaml
```
[lab-user@bastion-6hrbs ~]$ cat .kcli/clusters/6hrbs/install-config.yaml

apiVersion: v1
baseDomain: ...
compute:
- name: worker
  replicas: 3
controlPlane:
  name: master
  replicas: 3
metadata:
  name: 6hrbs
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
  - cidr: 10.132.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    failureDomains:
    - name: default
      region: default
      server: ...
      topology:
        computeCluster: ...
        datacenter: ...
        datastore: ...
        networks:
        - ...
        folder: ...
      zone: default
    vcenters:
    - datacenters:
      - Datacenter
      server: ...
      user: ...
      password: ...
      port: 443
pullSecret: ...
```
