### ISSUE TITLE
[Usage] Create VMs attached to a bridge to the external network

### ISSUE THREAD

**Issue by alvarolop** [karmab/kcli#738]
Hello, 

I'm trying to use `kcli` to provision some VMs in a baremetal node on AWS. The scenario is:

- OCP cluster deployed on AWS using IPI and provisioned with all ZTP needs.
- A baremetal EC2 instance deployed on the same network where I will create some VMs to simulate baremetal nodes to install SNO and MNO.

> NOTE: This scenario is similar to [LAB - 5G RAN Deployments on OpenShift](https://labs.sysdeseng.com/5g-ran-deployments-on-ocp-lab/4.16/index.html) and I'm heavily inspired in those instructions, but I need to externalize the Hub cluster with AAP, etc.

The issue that I encountered with `kcli` is that I configured the network on the node to convert `eth0` to a bridge `br0` so that I can launch VMs attached to the bridge.

```bash
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master br0 state UP group default qlen 1000
    link/ether 06:db:80:1d:92:15 brd ff:ff:ff:ff:ff:ff
    altname enp126s0
3: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default qlen 1000
    link/ether 06:db:80:1d:92:15 brd ff:ff:ff:ff:ff:ff
    inet 10.1.1.81/24 brd 10.1.1.255 scope global dynamic noprefixroute br0
       valid_lft 2934sec preferred_lft 2934sec
    inet6 fe80::6824:fb8:cef:1bf3/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

Then, I wanted to do something like this:

```yaml
    - name: Create vm tahitibob from centos8stream image and forcing memory to be 2G
      karmab.kcli.kcli_vm:
        name: testvm
        state: present
        image: centos8stream
        parameters:
          memory: 2048
          nets:
            # - default
            - name: br0 # Attach the VM to the br0 bridge
              nic: br0
              ip: 10.1.1.82
              mask: 255.255.255.0
              gateway: "{{ gateway }}"
```

To create a VM. Now I can list it:

```bash
$ kcli list vm
+--------+--------+-----------+---------------+-------+---------------+
|  Name  | Status |     Ip    |     Source    |  Plan |    Profile    |
+--------+--------+-----------+---------------+-------+---------------+
| testvm |   up   | 10.1.1.82 | centos8stream | kvirt | centos8stream |
+--------+--------+-----------+---------------+-------+---------------+
```

However, I cannot connect to it:

```bash
$ kcli list network
Listing Networks...
+---------+---------+------------------+------+---------+------+
| Network |   Type  |       Cidr       | Dhcp |  Domain | Mode |
+---------+---------+------------------+------+---------+------+
| br0     | bridged |       N/A        | N/A  |   N/A   | N/A  |
| default |  routed | 192.168.122.0/24 | True | default | nat  |
+---------+---------+------------------+------+---------+------+

$ kcli ssh testvm
ssh: connect to host 10.1.1.82 port 22: No route to host
```

Could you help me? Is this something that makes sense?
