### ISSUE TITLE
Openshift disconnected with kcli has a very minimal ICSP that does not cover operators

### ISSUE THREAD

**Issue by ElCoyote27** [karmab/kcli#762]
I am deploying disconnected OCP with kcli and a Proxy Registry (Nexus).

I am adding these apps to all of my deployments:

```
apps:
- autolabeller
- local-storage-operator
- odf-operator
- metallb-operator
- kubernetes-nmstate-operator
- kubevirt-hyperconverged
- advanced-cluster-management
- multicluster-engine
- cluster-logging
- topology-aware-lifecycle-manager
- sriov-network-operator

```

Once OCP is deployed and kcli starts deploying the Apps, I no longer see OCP using my registry.
When I look at the ICSP for the deployed cluster, the ICSP is super minimal:
```
$ oc get ImageContentSourcePolicy -o yaml
apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1alpha1
  kind: ImageContentSourcePolicy
  metadata:
    creationTimestamp: "2024-12-19T19:45:21Z"
    generation: 1
    name: image-policy
    resourceVersion: "648"
    uid: c8cc838c-7095-4923-a5e0-7735f2f66d54
  spec:
    repositoryDigestMirrors:
    - mirrors:
      - registry.lasthome.solace.krynn:5000/openshift-release-dev/ocp-v4.0-art-dev
      - registry.lasthome.solace.krynn:5000/openshift/release
      - registry.lasthome.solace.krynn:5000/openshift/release-images
      source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    - mirrors:
      - registry.lasthome.solace.krynn:5000/ocp-release
      - registry.lasthome.solace.krynn:5000/openshift-release-dev/ocp-release
      source: quay.io/ocp-release
kind: List
metadata:
  resourceVersion: ""

```

if I apply the following ICSP to my cluster before it starts deploying apps, -then- I see it pull the operators through my proxy registry.
I think it would be good if kcli would add an entry for each app/operator in the install-config.yaml prototype.
Here's the custom ICSP for all my clusters:

```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: krynn-registry
spec:
  repositoryDigestMirrors:
  - mirrors:
    - registry.lasthome.solace.krynn:5000/openshift-release-dev/ocp-release
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - registry.lasthome.solace.krynn:5000/openshift-release-dev/ocp-release
    source: registry.svc.ci.openshift.org/ocp/release
  - mirrors:
    - registry.lasthome.solace.krynn:5000/openshift-release-dev/ocp-release
    source: registry.ci.openshift.org/ocp/release
  - mirrors:
    - registry.lasthome.solace.krynn:5000/openshift-release-dev/ocp-v4.0-art-dev
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - registry.lasthome.solace.krynn:5000/openshift-community-operators
    source: quay.io/openshift-community-operators
  - mirrors:
    - registry.lasthome.solace.krynn:5000/jetstack
    source: quay.io/jetstack
  - mirrors:
    - registry.lasthome.solace.krynn:5000/rh-marketplace
    source: quay.io/rh-marketplace
  - mirrors:
    - registry.lasthome.solace.krynn:5000/openshift-release-dev/ocp-release
    source: cdn02.quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - registry.lasthome.solace.krynn:5000/openshift-release-dev/ocp-v4.0-art-dev
    source: cdn02.quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - registry.lasthome.solace.krynn:5000/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - registry.lasthome.solace.krynn:5000/container-native-virtualization
    source: registry.redhat.io/container-native-virtualization
  - mirrors:
    - registry.lasthome.solace.krynn:5000/rhacm2
    source: registry.redhat.io/rhacm2
  - mirrors:
    - registry.lasthome.solace.krynn:5000/multicluster-engine
    source: registry.redhat.io/multicluster-engine
  - mirrors:
    - registry.lasthome.solace.krynn:5000/odf4
    source: registry.redhat.io/odf4
  - mirrors:
    - registry.lasthome.solace.krynn:5000/ocs4
    source: registry.redhat.io/ocs4
  - mirrors:
    - registry.lasthome.solace.krynn:5000/redhat
    source: registry.redhat.io/redhat
  - mirrors:
    - registry.lasthome.solace.krynn:5000/rhceph
    source: registry.redhat.io/rhceph
  - mirrors:
    - registry.lasthome.solace.krynn:5000/rhscl
    source: registry.redhat.io/rhscl

```
With that ICSP applied on the side just before kcli deploys the openshift apps, I see OCP pulling the operators from my registry too.
