### ISSUE TITLE
Error while creating openshift on vmware plan

### ISSUE THREAD

**Issue by bemarek** [karmab/kcli#794]
I am trying to create openshift plan on VMWare:
```
$ kcli -d create plan -f vmware-plan.yaml 
Using sweaty-mellen as name of the plan
cluster:
- vmware-test:
    client: vmware-qpk58
    ctlplanes: 3
    domain: openshift-vmware.local
    kubetype: openshift
    tag: 4.18
    type: cluster
    version: stable
    workers: 6

Deploying Cluster entries...
Deploying Cluster vmware-test...
Couldnt find topfolder /SDDC-Datacenter/Workloads
Couldn't connect to client vmware-qpk58. Leaving...
```

Client definition is as below:
```
vmware-qpk58:                   
  type: vsphere                 
  host: ************
  user: "********"    
  password: ?secret             
  datacenter: SDDC-Datacenter   
  cluster: "Cluster-1"          
  pool: "workload_share_dwPsq"  
  basefolder: /SDDC-Datacenter/Workloads/sandbox-qpk58
  import_network: segment-sandbox-qpk58
```
I've set the path like above being suggested by this issue https://github.com/karmab/kcli/issues/611, which seems to be related to similar environment. However, when querying this VMWare environment with govc, the path is different:
```
$ govc ls /SDDC-Datacenter/vm/Workloads
/SDDC-Datacenter/vm/Workloads/sandbox-qpk58
```
But even setting the basefolder to /SDDC-Datacenter/vm/Workloads/sandbox-qpk58 the error is the same.
```
$ kcli -d create plan -f vmware-plan.yaml 
Using jovial-ablonde as name of the plan
cluster:
- vmware-test:
    client: vmware-qpk58
    ctlplanes: 3
    domain: openshift-vmware.local
    kubetype: openshift
    tag: 4.18
    type: cluster
    version: stable
    workers: 6

Deploying Cluster entries...
Deploying Cluster vmware-test...
Couldnt find topfolder /SDDC-Datacenter/vm/Workloads
Couldn't connect to client vmware-qpk58. Leaving...
```
